// Service-specific onboarding quiz configurations

export interface QuizOption {
  label: string;
  desc?: string;
}

export interface QuizStep {
  question: string;
  subtitle?: string;
  type: 'single' | 'multi';
  key: string;
  options: QuizOption[];
}

export interface ServiceOnboardingConfig {
  serviceSlug: string;
  serviceName: string;
  accentColor: string;
  glowHsl: string;
  headerLabel: string;
  headline: string;
  subtitle: string;
  steps: QuizStep[];
}

export const SERVICE_ONBOARDING: Record<string, ServiceOnboardingConfig> = {
  'custom-web-development': {
    serviceSlug: 'custom-web-development',
    serviceName: 'Custom Web Development',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// custom_web_dev :: onboarding',
    headline: "Let's scope your web project",
    subtitle: '6 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'What type of website do you need?',
        subtitle: 'Select the best match.',
        type: 'single',
        key: 'project_type',
        options: [
          { label: 'Business / Corporate Site', desc: 'Company website with multiple pages' },
          { label: 'SaaS / Web Application', desc: 'Interactive app with user accounts' },
          { label: 'E-Commerce Store', desc: 'Online shop with product catalogue' },
          { label: 'Landing Page / Microsite', desc: 'Single focused page for a campaign' },
          { label: 'Portfolio / Personal Brand', desc: 'Showcase your work or personal brand' },
          { label: 'Blog / Content Platform', desc: 'Publishing-focused with CMS' },
        ],
      },
      {
        question: 'Do you have an existing website?',
        subtitle: 'This helps us understand your starting point.',
        type: 'single',
        key: 'existing_site',
        options: [
          { label: 'No — starting from scratch', desc: 'Brand new build' },
          { label: 'Yes — needs a complete redesign', desc: 'Rebuild from the ground up' },
          { label: 'Yes — needs improvements', desc: 'Enhance and optimise what exists' },
          { label: 'Yes — migrating to new tech', desc: 'Moving to a modern framework' },
        ],
      },
      {
        question: 'Which features are essential?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'features_needed',
        options: [
          { label: 'Contact / Lead Forms' },
          { label: 'User Authentication' },
          { label: 'Payment / Checkout' },
          { label: 'CMS / Blog' },
          { label: 'Admin Dashboard' },
          { label: 'API Integrations' },
          { label: 'Search Functionality' },
          { label: 'Analytics & Tracking' },
          { label: 'Multi-language Support' },
          { label: 'Booking / Scheduling' },
        ],
      },
      {
        question: 'Any design preferences?',
        subtitle: 'Select all that resonate.',
        type: 'multi',
        key: 'design_prefs',
        options: [
          { label: 'Minimal & Clean' },
          { label: 'Bold & Colorful' },
          { label: 'Dark Theme / Techy' },
          { label: 'Corporate & Professional' },
          { label: 'Creative / Artistic' },
          { label: 'Match existing branding' },
        ],
      },
      {
        question: "What's your budget range?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $1K', desc: 'Lean & focused' },
          { label: '$1K – $5K', desc: 'Most popular range' },
          { label: '$5K – $10K', desc: 'Premium builds' },
          { label: '$10K+', desc: 'Enterprise-grade' },
        ],
      },
      {
        question: "What's your timeline?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'ASAP', desc: 'Need it yesterday' },
          { label: '1 – 3 months', desc: 'Standard timeline' },
          { label: '3 – 6 months', desc: 'No rush' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'responsive-design': {
    serviceSlug: 'responsive-design',
    serviceName: 'Responsive Design',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// responsive_design :: onboarding',
    headline: "Let's make your site work everywhere",
    subtitle: '5 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'What best describes your situation?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'project_type',
        options: [
          { label: 'Existing site — not mobile-friendly', desc: 'Needs a responsive overhaul' },
          { label: 'New build — mobile-first', desc: 'Starting fresh with responsive design' },
          { label: 'Partial issues — some pages break', desc: 'Fix specific breakpoints or pages' },
          { label: 'App or dashboard — complex layouts', desc: 'Tables, sidebars, data-heavy UI' },
        ],
      },
      {
        question: 'Which devices matter most?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'target_devices',
        options: [
          { label: 'Smartphones (iOS & Android)' },
          { label: 'Tablets / iPads' },
          { label: 'Laptops & Desktops' },
          { label: 'Large / Ultra-wide monitors' },
          { label: 'Kiosks / POS / Embedded screens' },
        ],
      },
      {
        question: 'What are your top priorities?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'priorities',
        options: [
          { label: 'Fast load times on mobile' },
          { label: 'Touch-friendly navigation' },
          { label: 'Readable text without zooming' },
          { label: 'Images & media that scale properly' },
          { label: 'Consistent look across browsers' },
          { label: 'Accessible / WCAG compliant' },
        ],
      },
      {
        question: "What's your budget range?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $1K', desc: 'Lean & focused' },
          { label: '$1K – $3K', desc: 'Most popular range' },
          { label: '$3K – $7K', desc: 'Comprehensive overhaul' },
          { label: '$7K+', desc: 'Enterprise-grade' },
        ],
      },
      {
        question: "What's your timeline?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'ASAP', desc: 'Need it yesterday' },
          { label: '2 – 4 weeks', desc: 'Standard timeline' },
          { label: '1 – 3 months', desc: 'No rush' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'ux-ui-design': {
    serviceSlug: 'ux-ui-design',
    serviceName: 'UX/UI Design',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// ux_ui_design :: onboarding',
    headline: "Let's design something users love",
    subtitle: '6 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'What do you need designed?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'project_scope',
        options: [
          { label: 'Brand-new product design', desc: 'Starting from scratch' },
          { label: 'Redesign of existing product', desc: 'Refresh or overhaul' },
          { label: 'Design system / component library', desc: 'Tokens, components, docs' },
          { label: 'Specific pages or flows', desc: 'Checkout, onboarding, dashboard, etc.' },
        ],
      },
      {
        question: 'What type of product?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'product_type',
        options: [
          { label: 'Marketing website' },
          { label: 'SaaS / Web app' },
          { label: 'E-Commerce store' },
          { label: 'Mobile app (iOS / Android)' },
          { label: 'Internal tool / Dashboard' },
        ],
      },
      {
        question: 'Which deliverables do you need?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'deliverables',
        options: [
          { label: 'Wireframes & user flows' },
          { label: 'High-fidelity mockups' },
          { label: 'Interactive prototype (Figma)' },
          { label: 'Design system / style guide' },
          { label: 'Iconography & illustrations' },
          { label: 'Developer-ready handoff specs' },
        ],
      },
      {
        question: 'What style direction resonates?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'style_direction',
        options: [
          { label: 'Minimal & Clean' },
          { label: 'Bold & Expressive' },
          { label: 'Dark & Techy' },
          { label: 'Warm & Friendly' },
          { label: 'Corporate & Professional' },
          { label: 'Match existing branding' },
        ],
      },
      {
        question: "What's your budget range?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $2K', desc: 'Lean scope' },
          { label: '$2K – $5K', desc: 'Most popular range' },
          { label: '$5K – $15K', desc: 'Full product design' },
          { label: '$15K+', desc: 'Enterprise / multi-product' },
        ],
      },
      {
        question: "What's your timeline?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'ASAP', desc: 'Need it yesterday' },
          { label: '2 – 4 weeks', desc: 'Standard timeline' },
          { label: '1 – 3 months', desc: 'Detailed process' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'cms-integration': {
    serviceSlug: 'cms-integration',
    serviceName: 'CMS Integration',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// cms_integration :: onboarding',
    headline: "Let's set up your content management",
    subtitle: '5 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'Do you have a CMS preference?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'cms_platform',
        options: [
          { label: 'WordPress', desc: 'Traditional or headless' },
          { label: 'Sanity', desc: 'Flexible, developer-friendly' },
          { label: 'Strapi', desc: 'Open-source headless CMS' },
          { label: 'Contentful', desc: 'Enterprise-grade headless' },
          { label: 'Not sure — advise me', desc: "We'll recommend the best fit" },
        ],
      },
      {
        question: 'What type of content will you manage?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'content_types',
        options: [
          { label: 'Blog posts / Articles' },
          { label: 'Product listings' },
          { label: 'Landing pages' },
          { label: 'Team / Staff profiles' },
          { label: 'FAQs / Knowledge base' },
          { label: 'Case studies / Portfolio' },
          { label: 'Multi-language content' },
        ],
      },
      {
        question: 'How large is your content team?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'team_size',
        options: [
          { label: 'Just me', desc: 'Solo content creator' },
          { label: '2 – 5 people', desc: 'Small team' },
          { label: '6 – 15 people', desc: 'Medium team with roles' },
          { label: '15+', desc: 'Large team, need workflows' },
        ],
      },
      {
        question: "What's your budget range?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $1K', desc: 'Basic setup' },
          { label: '$1K – $3K', desc: 'Most popular range' },
          { label: '$3K – $8K', desc: 'Custom content models' },
          { label: '$8K+', desc: 'Enterprise integration' },
        ],
      },
      {
        question: "What's your timeline?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'ASAP', desc: 'Need it yesterday' },
          { label: '1 – 3 weeks', desc: 'Standard timeline' },
          { label: '1 – 2 months', desc: 'Detailed setup' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'rent-a-website': {
    serviceSlug: 'rent-a-website',
    serviceName: 'Rent-A-Website',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// rent_a_website :: onboarding',
    headline: "Let's get you online — zero upfront",
    subtitle: '6 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'What type of business are you?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'business_type',
        options: [
          { label: 'Local service business', desc: 'Plumber, salon, trainer, etc.' },
          { label: 'Restaurant / Café / Bar', desc: 'Menu, reservations, location' },
          { label: 'Professional services', desc: 'Consultant, lawyer, accountant' },
          { label: 'E-Commerce / Retail', desc: 'Sell products online' },
          { label: 'Startup / New venture', desc: 'Just getting started' },
          { label: 'Other', desc: "We'll figure it out together" },
        ],
      },
      {
        question: 'How many pages do you need?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'page_count',
        options: [
          { label: '1 – 3 pages', desc: 'Landing page + basics' },
          { label: '4 – 7 pages', desc: 'Standard business site' },
          { label: '8 – 15 pages', desc: 'Content-rich site' },
          { label: '15+', desc: 'Large site with many sections' },
        ],
      },
      {
        question: 'Which features do you need?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'features_needed',
        options: [
          { label: 'Contact / Lead capture forms' },
          { label: 'Blog / CMS' },
          { label: 'AI chatbot' },
          { label: 'E-commerce / Online store' },
          { label: 'Online booking / Scheduling' },
          { label: 'Google Analytics & Search Console' },
          { label: 'Social media integration' },
          { label: 'WhatsApp click-to-chat' },
          { label: 'Heatmap + conversion tracking' },
          { label: 'Workflow automations (n8n)' },
        ],
      },
      {
        question: 'Do you have existing branding?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'branding_status',
        options: [
          { label: 'Yes — full brand kit', desc: 'Logo, colours, fonts ready' },
          { label: 'Partial — logo only', desc: 'Need help with the rest' },
          { label: 'No — need everything', desc: "We'll create your brand look" },
        ],
      },
      {
        question: 'Which plan fits your needs?',
        subtitle: 'Pre-selected from pricing — you can change it.',
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Launch — $49/mo', desc: '5 pages, hosting + SSL, SEO foundation, 1 update/mo · Setup $199' },
          { label: 'Grow — $99/mo', desc: '10 pages, CMS + blog, lead forms, monthly SEO report · Setup $299' },
          { label: 'Dominate — $199/mo', desc: 'Unlimited pages, AI chatbot, automations, priority support · Setup $499' },
          { label: 'Not sure — advise me', desc: "We'll recommend the best fit for your business" },
        ],
      },
      {
        question: "When do you want to go live?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'ASAP', desc: 'Need it this week' },
          { label: '2 – 3 weeks', desc: 'Standard timeline' },
          { label: '1 – 2 months', desc: 'No rush' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'data-driven-seo': {
    serviceSlug: 'data-driven-seo',
    serviceName: 'Data-Driven SEO',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// data_driven_seo :: onboarding',
    headline: "Let's dominate your search results",
    subtitle: '6 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: "What's your current SEO situation?",
        subtitle: 'Select one.',
        type: 'single',
        key: 'seo_maturity',
        options: [
          { label: 'Never done SEO', desc: 'Starting from zero' },
          { label: 'Some basics in place', desc: 'Meta tags, basic keywords' },
          { label: 'Active SEO — need improvement', desc: 'Doing it but not seeing results' },
          { label: 'Strong SEO — need scaling', desc: 'Rankings good, want more' },
        ],
      },
      {
        question: 'What are your primary SEO goals?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'seo_goals',
        options: [
          { label: 'Increase organic traffic' },
          { label: 'Rank for specific keywords' },
          { label: 'Generate more leads / enquiries' },
          { label: 'Improve local search visibility' },
          { label: 'Fix technical SEO issues' },
          { label: 'Build content authority' },
          { label: 'Outrank specific competitors' },
        ],
      },
      {
        question: 'What industry are you in?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'industry',
        options: [
          { label: 'E-Commerce / Retail' },
          { label: 'SaaS / Technology' },
          { label: 'Professional services' },
          { label: 'Healthcare / Wellness' },
          { label: 'Real estate / Property' },
          { label: 'Other' },
        ],
      },
      {
        question: 'Do you have a content strategy?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'content_status',
        options: [
          { label: 'No blog or content', desc: 'Need to start from scratch' },
          { label: 'Some content — inconsistent', desc: 'Publish occasionally' },
          { label: 'Regular publishing', desc: 'Blog active, need optimisation' },
          { label: 'Content team in place', desc: 'Need SEO direction for writers' },
        ],
      },
      {
        question: "What's your monthly SEO budget?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $500/mo', desc: 'Starter package' },
          { label: '$500 – $1.5K/mo', desc: 'Growth package' },
          { label: '$1.5K – $3K/mo', desc: 'Aggressive growth' },
          { label: '$3K+/mo', desc: 'Enterprise SEO' },
        ],
      },
      {
        question: "When do you want to start?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'Immediately', desc: 'Ready to go' },
          { label: 'Within 2 weeks', desc: 'Finalising plans' },
          { label: 'Next month', desc: 'Planning ahead' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'performance-optimization': {
    serviceSlug: 'performance-optimization',
    serviceName: 'Performance Optimization',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// performance_opt :: onboarding',
    headline: "Let's make your site lightning fast",
    subtitle: '5 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'What tech does your site run on?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'tech_stack',
        options: [
          { label: 'WordPress', desc: 'PHP-based CMS' },
          { label: 'React / Next.js', desc: 'Modern JS framework' },
          { label: 'Shopify / E-com platform', desc: 'Hosted e-commerce' },
          { label: 'Custom / Other framework', desc: 'Something else' },
          { label: "Not sure", desc: "We'll audit and find out" },
        ],
      },
      {
        question: 'What performance issues are you seeing?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'known_issues',
        options: [
          { label: 'Slow page loads' },
          { label: 'Poor Core Web Vitals scores' },
          { label: 'High bounce rate' },
          { label: 'Large page sizes / heavy images' },
          { label: 'Slow server response (TTFB)' },
          { label: 'Third-party script bloat' },
          { label: "Not sure — need a full audit" },
        ],
      },
      {
        question: 'How much traffic does your site get?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'traffic_volume',
        options: [
          { label: 'Under 1K visits/mo', desc: 'Low traffic' },
          { label: '1K – 10K visits/mo', desc: 'Growing site' },
          { label: '10K – 100K visits/mo', desc: 'Established site' },
          { label: '100K+ visits/mo', desc: 'High-traffic site' },
        ],
      },
      {
        question: "What's your budget range?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $1K', desc: 'Quick wins only' },
          { label: '$1K – $3K', desc: 'Comprehensive audit & fixes' },
          { label: '$3K – $7K', desc: 'Full performance overhaul' },
          { label: '$7K+', desc: 'Enterprise optimisation' },
        ],
      },
      {
        question: "What's your timeline?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'ASAP', desc: 'Site is losing revenue' },
          { label: '1 – 2 weeks', desc: 'Standard timeline' },
          { label: '1 – 2 months', desc: 'Part of a larger project' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'google-social-media-ads': {
    serviceSlug: 'google-social-media-ads',
    serviceName: 'Google & Social Media Ads',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// paid_ads :: onboarding',
    headline: "Let's maximise your ad spend",
    subtitle: '6 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'Which platforms do you want to advertise on?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'ad_platforms',
        options: [
          { label: 'Google Search Ads' },
          { label: 'Google Display / YouTube' },
          { label: 'Facebook / Instagram (Meta)' },
          { label: 'LinkedIn Ads' },
          { label: 'TikTok Ads' },
          { label: 'Not sure — advise me' },
        ],
      },
      {
        question: "What's your primary advertising goal?",
        subtitle: 'Select one.',
        type: 'single',
        key: 'ad_goal',
        options: [
          { label: 'Generate leads / enquiries', desc: 'Form fills, calls, sign-ups' },
          { label: 'Drive online sales', desc: 'E-commerce revenue' },
          { label: 'Brand awareness', desc: 'Reach & impressions' },
          { label: 'App installs / Downloads', desc: 'Drive app adoption' },
          { label: 'Retarget existing visitors', desc: 'Bring people back' },
        ],
      },
      {
        question: 'Have you run paid ads before?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'experience',
        options: [
          { label: 'Never — completely new', desc: 'Starting from scratch' },
          { label: 'Tried it — poor results', desc: 'Need expert help' },
          { label: 'Currently running ads', desc: 'Want better performance' },
          { label: 'Experienced — need scaling', desc: 'Ready to grow spend' },
        ],
      },
      {
        question: 'Do you have landing pages ready?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'landing_pages',
        options: [
          { label: 'Yes — optimised and ready', desc: 'Just need traffic' },
          { label: 'Yes — but need improvement', desc: 'Conversion rate is low' },
          { label: 'No — need them built', desc: 'Include in scope' },
        ],
      },
      {
        question: "What's your monthly ad budget?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $1K/mo', desc: 'Starter campaigns' },
          { label: '$1K – $5K/mo', desc: 'Growth stage' },
          { label: '$5K – $15K/mo', desc: 'Scaling campaigns' },
          { label: '$15K+/mo', desc: 'Enterprise ad spend' },
        ],
      },
      {
        question: "When do you want to launch?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'This week', desc: 'Ready to go' },
          { label: '2 – 4 weeks', desc: 'Strategy first' },
          { label: 'Next month', desc: 'Planning ahead' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'market-competitor-research': {
    serviceSlug: 'market-competitor-research',
    serviceName: 'Market & Competitor Research',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    headerLabel: '// market_research :: onboarding',
    headline: "Let's uncover your competitive edge",
    subtitle: '5 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'What industry are you in?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'industry',
        options: [
          { label: 'E-Commerce / Retail' },
          { label: 'SaaS / Technology' },
          { label: 'Professional services' },
          { label: 'Healthcare / Wellness' },
          { label: 'Real estate / Property' },
          { label: 'Other' },
        ],
      },
      {
        question: 'How many key competitors do you have?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'competitor_count',
        options: [
          { label: '1 – 3 competitors', desc: 'Niche market' },
          { label: '4 – 10 competitors', desc: 'Competitive market' },
          { label: '10+ competitors', desc: 'Crowded space' },
          { label: "Not sure", desc: "We'll identify them" },
        ],
      },
      {
        question: 'What do you want to learn?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'research_goals',
        options: [
          { label: 'Competitor SEO & keyword strategy' },
          { label: 'Competitor pricing & positioning' },
          { label: 'Market gaps & opportunities' },
          { label: 'Content & social media strategy' },
          { label: 'Audience demographics & behaviour' },
          { label: 'Industry trends & forecasts' },
        ],
      },
      {
        question: "What's your budget for this research?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $1K', desc: 'Quick overview' },
          { label: '$1K – $3K', desc: 'Detailed report' },
          { label: '$3K – $7K', desc: 'Comprehensive analysis' },
          { label: '$7K+', desc: 'Enterprise deep-dive' },
        ],
      },
      {
        question: "When do you need results?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'Within 1 week', desc: 'Urgent decision' },
          { label: '2 – 4 weeks', desc: 'Standard timeline' },
          { label: '1 – 2 months', desc: 'Thorough research' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'ai-powered-social-media': {
    serviceSlug: 'ai-powered-social-media',
    serviceName: 'AI-Powered Social Media',
    accentColor: 'text-neon-purple',
    glowHsl: '175 100% 42%',
    headerLabel: '// ai_social_media :: onboarding',
    headline: "Let's put your social on autopilot",
    subtitle: '6 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'Which platforms are you active on?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'platforms',
        options: [
          { label: 'Instagram' },
          { label: 'LinkedIn' },
          { label: 'Facebook' },
          { label: 'X / Twitter' },
          { label: 'TikTok' },
          { label: 'Not active yet — starting fresh' },
        ],
      },
      {
        question: 'How often do you want to post?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'posting_frequency',
        options: [
          { label: 'Daily', desc: 'Maximum visibility' },
          { label: '3 – 5 times per week', desc: 'Consistent presence' },
          { label: '1 – 2 times per week', desc: 'Steady cadence' },
          { label: 'Not sure — advise me', desc: "We'll recommend a schedule" },
        ],
      },
      {
        question: 'What content types do you need?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'content_types',
        options: [
          { label: 'Static image posts' },
          { label: 'Carousel / Slides' },
          { label: 'Short-form video (Reels / TikTok)' },
          { label: 'Stories' },
          { label: 'Text / Thread posts' },
          { label: 'Infographics' },
        ],
      },
      {
        question: 'How would you describe your brand voice?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'brand_voice',
        options: [
          { label: 'Professional & Authoritative' },
          { label: 'Friendly & Approachable' },
          { label: 'Bold & Provocative' },
          { label: 'Witty & Humorous' },
          { label: 'Educational & Informative' },
          { label: 'Not defined yet' },
        ],
      },
      {
        question: "Which package fits your needs?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Starter — $297/mo', desc: '8 posts/mo, 1 platform, templates & scheduling' },
          { label: 'Growth — $597/mo', desc: '16 posts/mo, 2 platforms, video edits & analytics' },
          { label: 'Power — $997/mo', desc: '24 posts/mo, 3 platforms, full-service with priority support' },
          { label: 'Not sure — advise me', desc: "We'll recommend the best fit" },
        ],
      },
      {
        question: "When do you want to start?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'This week', desc: 'Ready to go' },
          { label: '2 – 4 weeks', desc: 'After brand setup' },
          { label: 'Next month', desc: 'Planning phase' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'n8n-workflow-automation': {
    serviceSlug: 'n8n-workflow-automation',
    serviceName: 'n8n Workflow Automation',
    accentColor: 'text-neon-purple',
    glowHsl: '175 100% 42%',
    headerLabel: '// workflow_automation :: onboarding',
    headline: "Let's automate the boring stuff",
    subtitle: '5 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'Which tools are in your tech stack?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'tools_in_stack',
        options: [
          { label: 'Slack / Teams' },
          { label: 'Gmail / Outlook' },
          { label: 'HubSpot / CRM' },
          { label: 'Stripe / Payment platform' },
          { label: 'Google Sheets / Airtable' },
          { label: 'Notion / Project management' },
          { label: 'Shopify / E-commerce' },
          { label: 'Custom API / Database' },
        ],
      },
      {
        question: 'What processes do you want to automate?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'processes',
        options: [
          { label: 'Lead capture & CRM updates' },
          { label: 'Email sequences & follow-ups' },
          { label: 'Invoice & payment processing' },
          { label: 'Data sync between tools' },
          { label: 'Report generation' },
          { label: 'Customer onboarding' },
          { label: 'Social media scheduling' },
          { label: 'Inventory / Stock management' },
        ],
      },
      {
        question: 'How many workflows do you need?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'workflow_volume',
        options: [
          { label: '1 – 2 workflows', desc: 'Quick automation wins' },
          { label: '3 – 5 workflows', desc: 'Multiple process automation' },
          { label: '5 – 10 workflows', desc: 'Comprehensive automation' },
          { label: '10+', desc: 'Full business automation' },
        ],
      },
      {
        question: "What's your budget range?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $1K', desc: 'Simple automations' },
          { label: '$1K – $3K', desc: 'Multi-step workflows' },
          { label: '$3K – $7K', desc: 'Complex integrations' },
          { label: '$7K+', desc: 'Enterprise automation' },
        ],
      },
      {
        question: "What's your timeline?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'ASAP', desc: 'Manual work is killing us' },
          { label: '1 – 3 weeks', desc: 'Standard timeline' },
          { label: '1 – 2 months', desc: 'Part of a larger project' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },

  'content-strategy': {
    serviceSlug: 'content-strategy',
    serviceName: 'Content Strategy',
    accentColor: 'text-neon-purple',
    glowHsl: '175 100% 42%',
    headerLabel: '// content_strategy :: onboarding',
    headline: "Let's build your content engine",
    subtitle: '6 quick steps — takes under 2 minutes.',
    steps: [
      {
        question: 'What content do you need?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'content_types',
        options: [
          { label: 'Blog posts / Articles' },
          { label: 'Social media content' },
          { label: 'Email newsletters' },
          { label: 'Landing page copy' },
          { label: 'Case studies / White papers' },
          { label: 'Video scripts' },
          { label: 'Ad copy' },
        ],
      },
      {
        question: 'How often do you want to publish?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'publishing_frequency',
        options: [
          { label: 'Daily', desc: 'High-volume output' },
          { label: '2 – 3 times per week', desc: 'Consistent cadence' },
          { label: 'Weekly', desc: 'Quality over quantity' },
          { label: 'Bi-weekly / Monthly', desc: 'Thought leadership pieces' },
        ],
      },
      {
        question: 'Do you have existing content?',
        subtitle: 'Select one.',
        type: 'single',
        key: 'existing_content',
        options: [
          { label: 'No — starting from scratch', desc: 'Need everything created' },
          { label: 'Some — needs refreshing', desc: 'Outdated or underperforming' },
          { label: 'Lots — needs organising', desc: 'Content audit needed' },
          { label: 'Strong library — need more', desc: 'Scale what works' },
        ],
      },
      {
        question: 'Who is your target audience?',
        subtitle: 'Select all that apply.',
        type: 'multi',
        key: 'target_audience',
        options: [
          { label: 'B2B / Business buyers' },
          { label: 'B2C / Consumers' },
          { label: 'Technical / Developer audience' },
          { label: 'C-suite / Decision makers' },
          { label: 'Local community' },
          { label: 'Global / Multi-market' },
        ],
      },
      {
        question: "What's your monthly content budget?",
        type: 'single',
        key: 'budget',
        options: [
          { label: 'Under $500/mo', desc: 'Starter package' },
          { label: '$500 – $2K/mo', desc: 'Growth package' },
          { label: '$2K – $5K/mo', desc: 'Full content team' },
          { label: '$5K+/mo', desc: 'Enterprise content' },
        ],
      },
      {
        question: "When do you want to start?",
        type: 'single',
        key: 'timeline',
        options: [
          { label: 'This week', desc: 'Ready to go' },
          { label: '2 – 4 weeks', desc: 'Strategy first' },
          { label: 'Next month', desc: 'Planning phase' },
          { label: 'Just exploring', desc: 'Gathering info' },
        ],
      },
    ],
  },
};

export function getServiceOnboarding(slug: string): ServiceOnboardingConfig | undefined {
  return SERVICE_ONBOARDING[slug];
}
