export interface ServicePage {
  slug: string;
  pillarId: 'architecture' | 'growth' | 'autonomous';
  pillarLabel: string;
  accentColor: string;
  glowHsl: string;
  name: string;
  headline: string;
  subtitle: string;
  metaTitle: string;
  metaDescription: string;
  heroDescription: string;
  features: { title: string; description: string }[];
  process: { step: string; description: string }[];
  ctaHeadline: string;
  ctaDescription: string;
  ctaButtonLabel: string;
  contactPreset: string;
}

export const SERVICE_PAGES: ServicePage[] = [
  // ─── Pillar 01: Digital Architecture ───
  {
    slug: 'custom-web-development',
    pillarId: 'architecture',
    pillarLabel: 'Pillar 01 — Digital Architecture',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'Custom Web Development',
    headline: 'Custom Web Development',
    subtitle: 'Bespoke websites engineered for performance, scalability, and conversion.',
    metaTitle: 'Custom Web Development — Digiiworks',
    metaDescription: 'Get a bespoke, high-performance website built from the ground up. Digiiworks delivers custom web development with modern frameworks, SEO-ready architecture, and blazing speed.',
    heroDescription: 'Every business deserves a website that reflects its ambition. We build custom, hand-coded websites using modern frameworks like React, Next.js, and TypeScript — no templates, no shortcuts. From complex SaaS dashboards to sleek landing pages, we engineer digital experiences that load fast, rank high, and convert visitors into customers.',
    features: [
      { title: 'Modern Tech Stack', description: 'React, TypeScript, Next.js, Tailwind CSS — built with the tools that power the best products on the web.' },
      { title: 'Performance-First', description: 'Sub-second load times, optimised Core Web Vitals, and server-side rendering for maximum speed.' },
      { title: 'SEO-Ready Architecture', description: 'Semantic HTML, structured data, dynamic meta tags, and sitemap generation baked in from day one.' },
      { title: 'Scalable & Maintainable', description: 'Clean, modular codebases designed to grow with your business without technical debt.' },
    ],
    process: [
      { step: 'Discovery', description: 'We deep-dive into your goals, audience, and competitive landscape to define the blueprint.' },
      { step: 'Design & Prototype', description: 'Interactive wireframes and high-fidelity mockups for approval before a single line of code.' },
      { step: 'Development', description: 'Agile sprints with regular demos so you see progress and can steer the direction.' },
      { step: 'Launch & Optimise', description: 'Rigorous testing, performance tuning, and a smooth go-live followed by ongoing support.' },
    ],
    ctaHeadline: 'Ready to Build Something Exceptional?',
    ctaDescription: 'Tell us about your project and we\'ll craft a custom solution engineered for your success.',
    ctaButtonLabel: 'Start Your Project',
    contactPreset: 'Custom Web Development',
  },
  {
    slug: 'responsive-design',
    pillarId: 'architecture',
    pillarLabel: 'Pillar 01 — Digital Architecture',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'Responsive Design',
    headline: 'Responsive Design',
    subtitle: 'Pixel-perfect experiences across every device and screen size.',
    metaTitle: 'Responsive Web Design — Digiiworks',
    metaDescription: 'Deliver flawless user experiences on every screen. Digiiworks creates responsive designs that look stunning on mobile, tablet, and desktop with fluid layouts and adaptive components.',
    heroDescription: 'Over 60% of web traffic comes from mobile devices. We design and build fluid, responsive interfaces that adapt seamlessly to any screen — from smartphones to ultra-wide monitors. Every breakpoint is intentional, every interaction is touch-friendly, and every layout is tested across real devices.',
    features: [
      { title: 'Mobile-First Approach', description: 'Design starts at the smallest screen and scales up, ensuring mobile users get a first-class experience.' },
      { title: 'Fluid Grid Systems', description: 'Flexible layouts that adapt proportionally rather than snapping between rigid breakpoints.' },
      { title: 'Touch-Optimised Interactions', description: 'Larger tap targets, swipe gestures, and mobile-native patterns that feel intuitive.' },
      { title: 'Cross-Device Testing', description: 'Comprehensive QA across iOS, Android, Chrome, Safari, Firefox, and Edge on real devices.' },
    ],
    process: [
      { step: 'Audit', description: 'Analyse your current design across devices to identify gaps and opportunities.' },
      { step: 'Mobile Wireframes', description: 'Start with mobile layouts, then progressively enhance for larger screens.' },
      { step: 'Build & Test', description: 'Implement responsive CSS with real-device testing at every stage.' },
      { step: 'Optimise', description: 'Fine-tune performance, images, and interactions for each breakpoint.' },
    ],
    ctaHeadline: 'Make Your Site Work Everywhere',
    ctaDescription: 'Let\'s ensure your customers get a flawless experience on any device they use.',
    ctaButtonLabel: 'Get Responsive Design',
    contactPreset: 'Responsive Design',
  },
  {
    slug: 'ux-ui-design',
    pillarId: 'architecture',
    pillarLabel: 'Pillar 01 — Digital Architecture',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'UX/UI Design',
    headline: 'UX/UI Design',
    subtitle: 'Intuitive interfaces designed around user behaviour and business goals.',
    metaTitle: 'UX/UI Design Services — Digiiworks',
    metaDescription: 'Create intuitive, beautiful interfaces that convert. Digiiworks delivers research-driven UX/UI design with user journey mapping, prototyping, and design systems.',
    heroDescription: 'Great design isn\'t just about aesthetics — it\'s about reducing friction and guiding users toward action. We combine behavioural research, data analysis, and visual design to create interfaces that users love and businesses profit from. Every button placement, colour choice, and micro-interaction is backed by intent.',
    features: [
      { title: 'User Research & Personas', description: 'Deep understanding of your target audience through interviews, analytics, and competitive analysis.' },
      { title: 'Wireframing & Prototyping', description: 'Interactive prototypes you can click through before development begins — saving time and money.' },
      { title: 'Design Systems', description: 'Scalable component libraries with consistent typography, colour, and spacing tokens.' },
      { title: 'Conversion Optimisation', description: 'Data-informed layouts that guide users through funnels and maximise conversion rates.' },
    ],
    process: [
      { step: 'Research', description: 'User interviews, competitor audits, and analytics review to inform design decisions.' },
      { step: 'Information Architecture', description: 'Sitemap and user flow mapping to structure content logically.' },
      { step: 'Visual Design', description: 'High-fidelity mockups with your brand identity applied across all key pages.' },
      { step: 'Handoff & QA', description: 'Developer-ready specs with interactive prototypes and design token documentation.' },
    ],
    ctaHeadline: 'Design That Converts',
    ctaDescription: 'Let\'s create an interface your users will love and your competitors will envy.',
    ctaButtonLabel: 'Start UX/UI Project',
    contactPreset: 'UX/UI Design',
  },
  {
    slug: 'cms-integration',
    pillarId: 'architecture',
    pillarLabel: 'Pillar 01 — Digital Architecture',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'CMS Integration',
    headline: 'CMS Integration',
    subtitle: 'Effortless content management with headless or traditional CMS setups.',
    metaTitle: 'CMS Integration Services — Digiiworks',
    metaDescription: 'Manage your website content with ease. Digiiworks integrates headless and traditional CMS platforms like WordPress, Sanity, and Strapi for seamless content workflows.',
    heroDescription: 'Your team shouldn\'t need a developer to update a blog post or change a hero image. We integrate powerful content management systems — whether headless (Sanity, Strapi, Contentful) or traditional (WordPress) — so your team can publish, edit, and manage content independently while your site stays fast and secure.',
    features: [
      { title: 'Headless CMS Options', description: 'Sanity, Strapi, Contentful — choose the platform that fits your workflow and scale.' },
      { title: 'WordPress Integration', description: 'Custom themes and headless WordPress setups for teams already in the ecosystem.' },
      { title: 'Content Modelling', description: 'Structured content types designed for reusability across pages, apps, and channels.' },
      { title: 'Editorial Workflows', description: 'Draft, review, and publish pipelines with role-based permissions for your team.' },
    ],
    process: [
      { step: 'Requirements', description: 'Understand your content types, team size, and publishing frequency.' },
      { step: 'Platform Selection', description: 'Recommend the best CMS based on your needs, budget, and technical requirements.' },
      { step: 'Integration', description: 'Connect the CMS to your frontend with APIs, webhooks, and preview modes.' },
      { step: 'Training', description: 'Hands-on training for your team so they\'re confident managing content day one.' },
    ],
    ctaHeadline: 'Take Control of Your Content',
    ctaDescription: 'Let\'s set up a CMS that empowers your team to publish without developer dependency.',
    ctaButtonLabel: 'Get CMS Integration',
    contactPreset: 'CMS Integration',
  },
  {
    slug: 'rent-a-website',
    pillarId: 'architecture',
    pillarLabel: 'Pillar 01 — Digital Architecture',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'Rent-A-Website',
    headline: 'Rent-A-Website',
    subtitle: 'Professional site, zero upfront cost. Pay monthly, worry about nothing.',
    metaTitle: 'Rent-A-Website — Zero Upfront Cost | Digiiworks',
    metaDescription: 'Get a professional, custom-designed website with zero upfront cost. Digiiworks Rent-A-Website includes hosting, maintenance, updates, and support — all in one monthly fee.',
    heroDescription: 'Not every business has £5,000+ to spend on a website upfront. Our Rent-A-Website model gives you a professionally designed, fully managed website for a simple monthly fee. Hosting, maintenance, security updates, and support are all included. You focus on running your business — we handle everything else.',
    features: [
      { title: 'Zero Upfront Cost', description: 'No large initial investment. Get online immediately with a predictable monthly payment.' },
      { title: 'Fully Managed', description: 'Hosting, SSL, backups, security patches, and performance monitoring — all included.' },
      { title: 'Custom Design', description: 'Not a template. Your site is designed to match your brand and business goals.' },
      { title: 'Ongoing Support', description: 'Content updates, design tweaks, and technical support whenever you need it.' },
    ],
    process: [
      { step: 'Consultation', description: 'We discuss your business, goals, and what your website needs to achieve.' },
      { step: 'Design & Build', description: 'Custom design and development — typically live within 2-3 weeks.' },
      { step: 'Launch', description: 'Your site goes live with hosting, SSL, and monitoring configured.' },
      { step: 'Ongoing Care', description: 'Monthly maintenance, updates, and support for as long as you\'re subscribed.' },
    ],
    ctaHeadline: 'Get Online Without the Big Price Tag',
    ctaDescription: 'Start with zero upfront cost and a website that grows with your business.',
    ctaButtonLabel: 'Rent Your Website',
    contactPreset: 'Rent-A-Website',
  },

  // ─── Pillar 02: Growth Engine ───
  {
    slug: 'data-driven-seo',
    pillarId: 'growth',
    pillarLabel: 'Pillar 02 — Growth Engine',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'Data-Driven SEO',
    headline: 'Data-Driven SEO',
    subtitle: 'Keyword strategy, technical audits, and content optimisation for organic growth.',
    metaTitle: 'Data-Driven SEO Services — Digiiworks',
    metaDescription: 'Rank higher with data-driven SEO. Digiiworks delivers keyword research, technical audits, on-page optimisation, and content strategy to drive sustainable organic traffic.',
    heroDescription: 'SEO isn\'t guesswork — it\'s engineering. We use data from Google Search Console, Ahrefs, and our AI agent Vantage to identify high-impact keywords, fix technical issues, and create content strategies that compound over time. Every recommendation is backed by data, every result is measurable.',
    features: [
      { title: 'Technical SEO Audits', description: 'Comprehensive crawl analysis covering indexation, Core Web Vitals, schema markup, and site architecture.' },
      { title: 'Keyword Research & Mapping', description: 'Data-driven keyword strategy aligned to search intent and mapped to your content funnel.' },
      { title: 'On-Page Optimisation', description: 'Title tags, meta descriptions, internal linking, and content structure optimised for rankings.' },
      { title: 'Content Strategy', description: 'Topic clusters and editorial calendars designed to build topical authority in your niche.' },
    ],
    process: [
      { step: 'Audit', description: 'Full technical and content audit to identify quick wins and long-term opportunities.' },
      { step: 'Strategy', description: 'Keyword research, competitor gap analysis, and a prioritised action plan.' },
      { step: 'Execution', description: 'On-page fixes, content creation, and technical improvements rolled out in sprints.' },
      { step: 'Reporting', description: 'Monthly performance reports with rankings, traffic, and conversion data.' },
    ],
    ctaHeadline: 'Dominate Search Results',
    ctaDescription: 'Let\'s build an SEO strategy that drives consistent, high-quality organic traffic.',
    ctaButtonLabel: 'Start SEO Campaign',
    contactPreset: 'Data-Driven SEO',
  },
  {
    slug: 'performance-optimization',
    pillarId: 'growth',
    pillarLabel: 'Pillar 02 — Growth Engine',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'Performance Optimization',
    headline: 'Performance Optimization',
    subtitle: 'Speed, Core Web Vitals, and server-level tuning for peak performance.',
    metaTitle: 'Website Performance Optimization — Digiiworks',
    metaDescription: 'Make your website blazing fast. Digiiworks optimises Core Web Vitals, server response times, image delivery, and caching for maximum speed and better Google rankings.',
    heroDescription: 'A one-second delay in page load can cost you 7% in conversions. We obsess over performance — from server response times and image compression to JavaScript bundle sizes and caching strategies. Our goal: sub-second loads, green Core Web Vitals, and a silky-smooth user experience that Google rewards with higher rankings.',
    features: [
      { title: 'Core Web Vitals', description: 'LCP, FID, and CLS optimisation to meet Google\'s performance benchmarks.' },
      { title: 'Image & Asset Optimisation', description: 'Next-gen formats (WebP, AVIF), lazy loading, and responsive image delivery.' },
      { title: 'Code Splitting & Bundling', description: 'Reduce JavaScript payload with tree-shaking, dynamic imports, and efficient bundling.' },
      { title: 'CDN & Caching Strategy', description: 'Global content delivery with intelligent caching for instant repeat visits.' },
    ],
    process: [
      { step: 'Benchmark', description: 'Lighthouse audits, WebPageTest analysis, and real-user monitoring baseline.' },
      { step: 'Diagnose', description: 'Identify the biggest performance bottlenecks and their business impact.' },
      { step: 'Optimise', description: 'Implement fixes in priority order — server, assets, code, then third-party scripts.' },
      { step: 'Monitor', description: 'Ongoing performance monitoring to catch regressions before users notice.' },
    ],
    ctaHeadline: 'Make Your Site Lightning Fast',
    ctaDescription: 'Speed is money. Let\'s optimise your site for peak performance and better conversions.',
    ctaButtonLabel: 'Boost Performance',
    contactPreset: 'Performance Optimization',
  },
  {
    slug: 'google-social-media-ads',
    pillarId: 'growth',
    pillarLabel: 'Pillar 02 — Growth Engine',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'Google & Social Media Ads',
    headline: 'Google & Social Media Ads',
    subtitle: 'Targeted ad campaigns across Google, Meta, and beyond.',
    metaTitle: 'Google & Social Media Ads Management — Digiiworks',
    metaDescription: 'Drive targeted traffic with expertly managed Google Ads and social media campaigns. Digiiworks handles strategy, creative, bidding, and optimisation for maximum ROI.',
    heroDescription: 'Paid advertising should be a profit centre, not a money pit. We build and manage ad campaigns across Google Search, Display, YouTube, Meta (Facebook & Instagram), and LinkedIn — with a relentless focus on ROAS. From audience targeting and ad creative to bid strategy and landing page optimisation, every pound spent is tracked and optimised.',
    features: [
      { title: 'Google Ads Management', description: 'Search, Display, Shopping, and YouTube campaigns with granular keyword targeting and bid management.' },
      { title: 'Social Media Advertising', description: 'Meta, LinkedIn, and TikTok campaigns with audience segmentation and creative testing.' },
      { title: 'Landing Page Optimisation', description: 'High-converting landing pages designed to maximise your ad spend ROI.' },
      { title: 'Analytics & Attribution', description: 'Full-funnel tracking with conversion attribution so you know exactly what\'s working.' },
    ],
    process: [
      { step: 'Strategy', description: 'Define goals, audiences, budgets, and channel mix based on your market.' },
      { step: 'Creative', description: 'Ad copy, visuals, and landing pages designed for each platform and audience.' },
      { step: 'Launch & Test', description: 'A/B testing across ad variations, audiences, and placements to find winners.' },
      { step: 'Scale', description: 'Double down on what works, cut what doesn\'t, and continuously optimise for ROI.' },
    ],
    ctaHeadline: 'Maximise Your Ad Spend',
    ctaDescription: 'Let\'s build campaigns that drive real revenue — not just clicks.',
    ctaButtonLabel: 'Launch Ad Campaigns',
    contactPreset: 'Google & Social Media Ads',
  },
  {
    slug: 'market-competitor-research',
    pillarId: 'growth',
    pillarLabel: 'Pillar 02 — Growth Engine',
    accentColor: 'text-neon-blue',
    glowHsl: '184 100% 50%',
    name: 'Market & Competitor Research',
    headline: 'Market & Competitor Research',
    subtitle: 'Deep-dive analysis to find gaps and opportunities in your market.',
    metaTitle: 'Market & Competitor Research — Digiiworks',
    metaDescription: 'Uncover market opportunities and outsmart competitors. Digiiworks provides in-depth competitor analysis, market gap identification, and strategic positioning insights.',
    heroDescription: 'You can\'t win a game you don\'t understand. We conduct deep competitor analysis, market trend research, and audience insight studies to identify the gaps your brand can exploit. From SEO competitor benchmarking to pricing analysis and content gap mapping, we give you the intelligence to make strategic, data-backed decisions.',
    features: [
      { title: 'Competitor SEO Analysis', description: 'Discover your competitors\' top keywords, backlinks, and content strategies to outrank them.' },
      { title: 'Market Gap Identification', description: 'Find underserved audiences and unmet needs in your market that represent growth opportunities.' },
      { title: 'Pricing & Positioning', description: 'Benchmark your pricing against competitors and identify optimal positioning strategies.' },
      { title: 'Trend Monitoring', description: 'Stay ahead of industry shifts with ongoing market intelligence powered by our AI agents.' },
    ],
    process: [
      { step: 'Scope', description: 'Define your competitive landscape, target market, and key questions to answer.' },
      { step: 'Research', description: 'Deep-dive analysis using industry tools, AI agents, and manual investigation.' },
      { step: 'Analysis', description: 'Synthesise findings into actionable insights with clear strategic recommendations.' },
      { step: 'Deliver', description: 'Comprehensive report with visualised data, competitor profiles, and an action plan.' },
    ],
    ctaHeadline: 'Know Your Market Inside Out',
    ctaDescription: 'Get the competitive intelligence you need to make smarter strategic decisions.',
    ctaButtonLabel: 'Get Market Research',
    contactPreset: 'Market & Competitor Research',
  },

  // ─── Pillar 03: Autonomous Agency ───
  {
    slug: 'ai-powered-social-media',
    pillarId: 'autonomous',
    pillarLabel: 'Pillar 03 — Autonomous Agency',
    accentColor: 'text-neon-purple',
    glowHsl: '175 100% 42%',
    name: 'AI-Powered Social Media',
    headline: 'AI-Powered Social Media',
    subtitle: 'Content creation and scheduling driven by AI agents.',
    metaTitle: 'AI-Powered Social Media Management — Digiiworks',
    metaDescription: 'Automate your social media with AI. Digiiworks AI agents create, schedule, and optimise social content across platforms — generating engagement while you focus on business.',
    heroDescription: 'Social media demands consistency, creativity, and speed — three things AI excels at. Our agents Vantage and Pixel work together to research trending topics, generate on-brand content, create visuals, and schedule posts across your platforms. Human creativity sets the strategy; AI handles the relentless execution.',
    features: [
      { title: 'AI Content Generation', description: 'Pixel creates platform-optimised posts, captions, and visuals tailored to your brand voice.' },
      { title: 'Trend-Driven Strategy', description: 'Vantage monitors trends and competitor activity to keep your content relevant and timely.' },
      { title: 'Multi-Platform Scheduling', description: 'Automated publishing across Instagram, LinkedIn, X/Twitter, and Facebook at optimal times.' },
      { title: 'Performance Analytics', description: 'Track engagement, reach, and growth with AI-generated insights and recommendations.' },
    ],
    process: [
      { step: 'Brand Setup', description: 'Define your brand voice, visual style, target audience, and content pillars.' },
      { step: 'AI Calibration', description: 'Train our agents on your brand guidelines and approve initial content samples.' },
      { step: 'Automated Execution', description: 'Vantage researches, Pixel creates, and content publishes on autopilot.' },
      { step: 'Review & Refine', description: 'Monthly performance reviews with strategy adjustments based on data.' },
    ],
    ctaHeadline: 'Put Social Media on Autopilot',
    ctaDescription: 'Let AI agents handle the daily grind while you focus on growing your business.',
    ctaButtonLabel: 'Automate Social Media',
    contactPreset: 'AI-Powered Social Media',
  },
  {
    slug: 'n8n-workflow-automation',
    pillarId: 'autonomous',
    pillarLabel: 'Pillar 03 — Autonomous Agency',
    accentColor: 'text-neon-purple',
    glowHsl: '280 99% 53%',
    name: 'n8n Workflow Automation',
    headline: 'n8n Workflow Automation',
    subtitle: 'Automate repetitive tasks across your entire tech stack.',
    metaTitle: 'n8n Workflow Automation — Digiiworks',
    metaDescription: 'Eliminate manual busywork with n8n workflow automation. Digiiworks builds custom automations connecting your tools — CRM, email, Slack, databases, and more.',
    heroDescription: 'Every hour your team spends on repetitive tasks is an hour stolen from growth. We design and build custom automation workflows using n8n — connecting your CRM, email, Slack, databases, payment systems, and dozens more tools into seamless, self-running pipelines. From lead nurturing sequences to invoice processing, if it\'s repetitive, we automate it.',
    features: [
      { title: 'Custom Workflow Design', description: 'Bespoke automation flows tailored to your specific business processes and tools.' },
      { title: '500+ App Integrations', description: 'Connect virtually any tool in your stack — Slack, HubSpot, Gmail, Stripe, Notion, and more.' },
      { title: 'Error Handling & Monitoring', description: 'Built-in retry logic, error alerts, and monitoring dashboards for reliable automation.' },
      { title: 'Self-Hosted & Secure', description: 'Your automations run on your infrastructure — full control, full privacy, zero vendor lock-in.' },
    ],
    process: [
      { step: 'Workflow Audit', description: 'Map your current processes to identify automation opportunities and ROI potential.' },
      { step: 'Design', description: 'Blueprint the automation flows with trigger conditions, logic branches, and integrations.' },
      { step: 'Build & Test', description: 'Develop the workflows in n8n with thorough testing and edge-case handling.' },
      { step: 'Deploy & Monitor', description: 'Go live with monitoring, alerts, and documentation for your team.' },
    ],
    ctaHeadline: 'Stop Doing What Robots Should',
    ctaDescription: 'Let\'s automate your repetitive workflows and free your team to focus on what matters.',
    ctaButtonLabel: 'Automate Workflows',
    contactPreset: 'n8n Workflow Automation',
  },
  {
    slug: 'content-strategy',
    pillarId: 'autonomous',
    pillarLabel: 'Pillar 03 — Autonomous Agency',
    accentColor: 'text-neon-purple',
    glowHsl: '280 99% 53%',
    name: 'Content Strategy',
    headline: 'Content Strategy',
    subtitle: 'AI-powered research, copywriting, and visuals by Vantage & Pixel.',
    metaTitle: 'AI Content Strategy — Digiiworks',
    metaDescription: 'Build a content engine powered by AI. Digiiworks agents Vantage and Pixel handle research, copywriting, and visual creation for blogs, social media, and marketing.',
    heroDescription: 'Content is the fuel that powers SEO, social media, and brand authority — but producing it consistently is a grind. Our AI agents Vantage (research & strategy) and Pixel (creation & design) work as a tireless content team. They research trending topics, analyse competitor content, write SEO-optimised articles, and generate matching visuals — all aligned to your brand voice.',
    features: [
      { title: 'AI-Powered Research', description: 'Vantage analyses search trends, competitor content, and audience interests to identify winning topics.' },
      { title: 'SEO-Optimised Writing', description: 'Blog posts, landing page copy, and articles written to rank — with natural language and proper structure.' },
      { title: 'Visual Content Creation', description: 'Pixel generates social graphics, blog images, and marketing visuals on-brand and on-demand.' },
      { title: 'Editorial Calendar', description: 'A data-driven publishing schedule that builds topical authority over time.' },
    ],
    process: [
      { step: 'Strategy Session', description: 'Define your content pillars, target keywords, and brand voice guidelines.' },
      { step: 'AI Research Phase', description: 'Vantage analyses your niche to build a prioritised content roadmap.' },
      { step: 'Content Production', description: 'AI-generated drafts reviewed by humans, then polished and published.' },
      { step: 'Measure & Iterate', description: 'Track content performance and refine the strategy based on real data.' },
    ],
    ctaHeadline: 'Build a Content Engine That Never Stops',
    ctaDescription: 'Let AI handle the heavy lifting while you maintain creative control.',
    ctaButtonLabel: 'Start Content Strategy',
    contactPreset: 'Content Strategy',
  },
];

export const getServiceBySlug = (slug: string): ServicePage | undefined =>
  SERVICE_PAGES.find((s) => s.slug === slug);
