project_id = "jiwyrsnwmlxoelrpowbq"

[functions.send-invoice-email]
verify_jwt = false

[functions.generate-recurring-invoices]
verify_jwt = false

[functions.create-yoco-checkout]
verify_jwt = false

[functions.yoco-webhook]
verify_jwt = false

[functions.get-invoice-public]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false